# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5ffbffdcb6427a8f44b17b1203e4ec91aa59c2320ce1d1015d63e27d9e479bddcb251d702372969b9e99cba526e65b87c93820858a1e1cdcaae50455fc585ad

test:
  secret_key_base: 04b4c24aa770acd7adbac8ff9f0768c425bde2f1962ec90a0219d251dc16b0c0378c3fecaf0bddcbbc020d8c3f4a16dbe53a009c4656f5124f3be2d0a051c2f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
